name: Publish images to Docker Hub

on:
  push:
    tags:
      - base-alpine/*
      - base-debian/*
      - k8s-dataflow/*

jobs:
  publish:
    name: Publish images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract release version from ref
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}

    - name: Build and push base-alpine
      if: startsWith(github.ref, 'refs/tags/base-alpine/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: snowplow/base-alpine
        dockerfile: base-alpine/Dockerfile
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        push: true

    - name: Build and push base-debian
      if: startsWith(github.ref, 'refs/tags/base-debian/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: snowplow/base-debian
        dockerfile: base-debian/Dockerfile
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        push: true

    - name: Build and push k8s-dataflow
      if: startsWith(github.ref, 'refs/tags/k8s-dataflow/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: snowplow/k8s-dataflow
        dockerfile: k8s-dataflow/Dockerfile
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        push: true
